name: Deploy Frontend
on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u harshveefin -p H@rsh056!
      - run: docker build -t cygnetops/react-test -f Dockerfile.dev .
      - run: docker run -e CI=true -p 3000:3000 cygnetops/react-test npm test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          application_name: frontend
          environment_name: frontend-env
          existing_bucket_name: elasticbeanstalk-ap-south-1-020873976878
          region: ap-south-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY}}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
